version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app_network
    depends_on:
      - db

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue_worker
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - ./src:/var/www
    networks:
      - app_network
    depends_on:
      - app
      - db

  nginx:
    image: nginx:1.25
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: